module.exports = {
  rules: {},
  configs: {
    default: {
      extends: [
        'plugin:import/errors',
        'plugin:import/warnings',
        'plugin:@typescript-eslint/eslint-recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:react/recommended',
        'plugin:react-hooks/recommended',
      ],
      plugins: [
        '@typescript-eslint',
        'import',
        'react',
      ],
      rules: {
        'accessor-pairs': 2,
        'array-bracket-spacing': [2, 'never'],
        'arrow-spacing': [2, { 'before': true, 'after': true }],
        'block-spacing': [2, 'always'],
        'brace-style': [2, '1tbs', { 'allowSingleLine': true }],
        'camelcase': [0, { 'properties': 'always' }],
        'comma-dangle': [2, 'always-multiline'],
        'comma-spacing': [2, { 'before': false, 'after': true }],
        'comma-style': [2, 'last'],
        'constructor-super': 2,
        'curly': 0,
        'dot-location': [2, 'property'],
        'eol-last': 2,
        'eqeqeq': 2,
        'generator-star-spacing': [2, { 'before': true, 'after': true }],
        'handle-callback-err': [2, '^(err|error)$'],
        'import/default': 2,
        'import/export': 2,
        'import/no-absolute-path': 2,
        'import/no-duplicates': 2,
        'import/no-self-import': 2,
        'import/no-unresolved': 2,
        'import/order': [2, { 'groups': ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'object'] }],
        'indent': [2, 2, { 'SwitchCase': 1 }],
        'jsx-quotes': [2, 'prefer-double'],
        'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
        'keyword-spacing': [2, { 'before': true, 'after': true }],
        'max-len': [2, { 'code': 120, 'ignoreComments': true, 'ignoreTrailingComments': true, 'ignoreUrls': true }],
        'new-cap': [2, { 'newIsCap': true, 'capIsNew': false }],
        'new-parens': 2,
        'no-array-constructor': 2,
        'no-caller': 2,
        'no-class-assign': 2,
        'no-cond-assign': 2,
        'no-console': 2,
        'no-const-assign': 2,
        'no-control-regex': 2,
        'no-debugger': 2,
        'no-delete-var': 2,
        'no-dupe-args': 2,
        'no-dupe-class-members': 2,
        'no-dupe-keys': 2,
        'no-duplicate-case': 2,
        'no-empty-character-class': 2,
        'no-empty-pattern': 2,
        'no-eval': 2,
        'no-ex-assign': 2,
        'no-extend-native': 2,
        'no-extra-bind': 2,
        'no-extra-boolean-cast': 2,
        'no-extra-parens': [2, 'functions'],
        'no-fallthrough': 2,
        'no-floating-decimal': 2,
        'no-func-assign': 2,
        'no-implied-eval': 2,
        'no-inner-declarations': [2, 'functions'],
        'no-invalid-regexp': 2,
        'no-irregular-whitespace': 2,
        'no-iterator': 2,
        'no-label-var': 2,
        'no-labels': [2, { 'allowLoop': false, 'allowSwitch': false }],
        'no-lone-blocks': 2,
        'no-mixed-spaces-and-tabs': 2,
        'no-multi-spaces': 2,
        'no-multi-str': 2,
        'no-multiple-empty-lines': [2, { 'max': 1 }],
        'no-new-object': 2,
        'no-new-require': 2,
        'no-new-symbol': 2,
        'no-new-wrappers': 2,
        'no-obj-calls': 2,
        'no-octal-escape': 2,
        'no-octal': 2,
        'no-path-concat': 2,
        'no-proto': 2,
        'no-redeclare': 2,
        'no-regex-spaces': 2,
        'no-return-assign': [2, 'except-parens'],
        'no-self-assign': 2,
        'no-self-compare': 2,
        'no-sequences': 2,
        'no-shadow-restricted-names': 2,
        'no-sparse-arrays': 2,
        'no-this-before-super': 2,
        'no-throw-literal': 2,
        'no-trailing-spaces': 2,
        'no-undef': 2,
        'no-unexpected-multiline': 2,
        'no-unmodified-loop-condition': 2,
        'no-unneeded-ternary': [2, { 'defaultAssignment': false }],
        'no-unreachable': 2,
        'no-unsafe-finally': 2,
        'no-unused-vars': [2, { 'vars': 'all', 'args': 'none' }],
        'no-useless-call': 2,
        'no-useless-computed-key': 2,
        'no-useless-constructor': 2,
        'no-useless-escape': 0,
        'no-whitespace-before-property': 2,
        'no-with': 2,
        'object-curly-spacing': [2, 'always', { 'objectsInObjects': true }],
        'one-var': [2, { 'initialized': 'never' }],
        'operator-linebreak': [2, 'after', { 'overrides': { '?': 'before', ':': 'before' } }],
        'padded-blocks': [2, 'never'],
        'prefer-const': 2,
        'quotes': [2, 'single', { 'avoidEscape': true, 'allowTemplateLiterals': true }],
        'react/display-name': 0,
        'react/jsx-boolean-value': [2, 'never'],
        'react/jsx-closing-bracket-location': 2,
        'react/jsx-equals-spacing': 2,
        'react/jsx-filename-extension': [2, { 'extensions': ['.jsx', '.tsx'] }],
        'react/jsx-handler-names': 'off',
        'react/jsx-indent-props': [2, 2],
        'react/jsx-indent': [2, 2],
        'react/jsx-key': 2,
        'react/jsx-no-bind': [2, { 'ignoreRefs': true }],
        'react/jsx-no-duplicate-props': 2,
        'react/jsx-no-literals': 0,
        'react/jsx-no-target-blank': 2,
        'react/jsx-no-undef': 2,
        'react/jsx-pascal-case': 2,
        'react/jsx-sort-props': 0,
        'react/jsx-tag-spacing': 2,
        'react/jsx-uses-react': 0,
        'react/jsx-uses-vars': 2,
        'react/no-array-index-key': 2,
        'react/no-children-prop': 2,
        'react/no-danger': 1,
        'react/no-deprecated': 2,
        'react/no-did-mount-set-state': 0,
        'react/no-did-update-set-state': 2,
        'react/no-direct-mutation-state': 2,
        'react/no-find-dom-node': 2,
        'react/no-is-mounted': 2,
        'react/no-multi-comp': [2, { 'ignoreStateless': true }],
        'react/no-set-state': 0,
        'react/no-unknown-property': 2,
        'react/no-unused-prop-types': 2,
        'react/no-will-update-set-state': 2,
        'react/prefer-stateless-function': 2,
        'react/prop-types': 0,
        'react/require-default-props': 2,
        'react/require-render-return': 2,
        'react/self-closing-comp': [2, { 'html': false }],
        'react/sort-comp': [
          2,
          {
            'order': [
              'static-properties',
              'static-methods',
              'state',
              'properties',
              'lifecycle',
              'everything-else',
              'render'
            ],
            'groups': {
              'static-properties': [
                'displayName',
                'propTypes',
                'contextTypes',
                'childContextTypes',
                'mixins',
                'statics'
              ],
              'lifecycle': [
                'getDefaultProps',
                'getInitialState',
                'constructor',
                'getChildContext',
                'componentWillMount',
                'componentDidMount',
                'componentWillReceiveProps',
                'shouldComponentUpdate',
                'componentWillUpdate',
                'componentDidUpdate',
                'componentWillUnmount'
              ],
            },
          },
        ],
        'react/sort-prop-types': 0,
        'react/style-prop-object': 2,
        'semi-spacing': [2, { 'before': false, 'after': true }],
        'semi': [2, 'always'],
        'space-before-blocks': [2, 'always'],
        'space-before-function-paren': [2, 'never'],
        'space-in-parens': [2, 'never'],
        'space-infix-ops': 2,
        'space-unary-ops': [2, { 'words': true, 'nonwords': false }],
        'spaced-comment': [2, 'always', { 'markers': ['global', 'globals', 'eslint', 'eslint-disable', '*package', '!', ','] }],
        'template-curly-spacing': [2, 'never'],
        'use-isnan': 2,
        'valid-typeof': 2,
        'wrap-iife': [2, 'any'],
        'yield-star-spacing': [2, 'both'],
        'yoda': [2, 'never'],
      },
    },
  },
};
